version: '2.1'
services:
  php:
#    build: .
    image: floatapp/php-apache:develop
    ports:
     - "80:80"
    volumes:
     - ./apache2/sites-enabled:/etc/apache2/sites-enabled
     - ./html:/var/www/html
