version: '2'
services:
  php:
    image: floatapp/php5.5:1.1
    ports:
     - "80:80"
    volumes:
     - ./apache2/sites-enabled:/etc/apache2/sites-enabled
     - ./sites:/var/www/html
    links:
     - mysql
     - redis

  redis:
    image: redis:3.2-alpine
    ports:
     - "6379:6379"
    volumes:
     - ./data/redis:/data
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf

  mysql:
    image: k0st/alpine-mariadb
    ports:
     - "3306:3306"
    volumes:
     - /data/mysql:/var/lib/mysql
    environment:
     - MYSQL_DATABASE=mydb
     - MYSQL_USER=myuser
     - MYSQL_PASSWORD=mypass 

  nginx:
    image: nginx:stable-alpine
    ports:
     - "443:443"
    volumes:
     - ./nginx/log:/var/log/nginx
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/files:/var/www/nginx:ro
    links:
     - php
     - notify

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8080:80"
    links:
     - mysql:db