version: '2'
services:
  php:
    build: .
    image: floatapp/docker-php-apache:5.6-1.0
    ports:
     - "80:80"
    volumes:
     - ./apache2/sites-enabled:/etc/apache2/sites-enabled
     - ./sites:/var/www/html
